version: "3.9"

services:

  gerenciamento:
    build:
      context: ./gerenciamento
    container_name: gerenciamento
    ports:
      - "5000:5000"
    volumes:
      - ./gerenciamento:/app
      - ./gerenciamento/database.db:/app/database.db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: python app.py


  reservas:

    build:
      context: ./reservas
    container_name: reservas
    ports:
      - "5001:5000" 
    volumes:
      - ./reservas:/app
      - ./reservas/database.db:/app/database.db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - GERENCIAMENTO_BASE_URL=http://gerenciamento:5000
    command: python app.py


  atividades-notas:
    build:
      context: ./atividades-notas
    container_name: atividades-notas
    ports:
      - "5002:5000"
    volumes:
      - ./atividades-notas:/app
      - ./atividades-notas/database.db:/app/database.db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - GERENCIAMENTO_BASE_URL=http://gerenciamento:5000
    command: python app.py