version: "3.9"

services:
  gerenciamento:
    build:
      context: ./Gerenciamento
    container_name: gerenciamento
    ports:
      - "5000:5000"
    volumes:
      - ./Gerenciamento:/app
      - ./data/gerenciamento.db:/app/data/gerenciamento.db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: python app.py


  reservas:
    build:
      context: ./Reservas
    container_name: reservas
    ports:
      - "5001:5000"
    volumes:
      - ./Reservas:/app
      - ./data/reservas.db:/app/data/reservas.db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - GERENCIAMENTO_BASE_URL=http://gerenciamento:5000
    command: python app.py


  atividades-notas:
    build:
      context: ./Atividade-Notas
    container_name: atividades-notas
    ports:
      - "5002:5000"
    volumes:
      - ./Atividade-Notas:/app
      - ./data/atividades-notas.db:/app/data/atividades-notas.db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - GERENCIAMENTO_BASE_URL=http://gerenciamento:5000
    command: python app.py